# SPDX-License-Identifier: GPL-2.0
#
# Makefile for GSWIP
#
obj-y += gswip-dev.o gswip-core.o gswip-mac.o

gswip-dev-y := gswip_dev.o
gswip-core-y := gswip_core.o gswip_port.o gswip_tbl.o
gswip-mac-y := mac_dev.o mac_cfg.o gswip_mac.o xgmac.o lmac.o

