# SPDX-License-Identifier: GPL-2.0-only
# Copyright (C) 2020 Intel Corporation

#
# Makefile for the Intel(R) Data Plane Function Linux Driver
#

obj-$(CONFIG_IDPF) += idpf.o

ccflags-y += -I${src}/../include -I${src}

idpf-y := \
	idpf_main.o \
	idpf_reg.o
